eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8700/eureka/
spring:
  data:
    cassandra:
      keyspace-name: simple_programming
      port: 9042
      contact-points: localhost
      username: cassandra
      password: cassandra